### ISSUE TITLE
Re-enable connection pool for OSGP components

### ISSUE THREAD

**Issue by kevinsmeets** [OSGP/Platform#115]
Some time ago connection pooling was removed from the OSGP components. Back then BoneCP was in use.

**Comment by klvries** [comment]
according to the logging at startup the connection pooling is activated and works as expected:
09:37:09.584 [localhost-startStop-1] INFO  (HikariDataSource.java:72) com.zaxxer.hikari.HikariDataSource - Hikari pool HikariPool-0 is starting.
09:37:30.141 [localhost-startStop-1] INFO  (HikariDataSource.java:72) com.zaxxer.hikari.HikariDataSource - Hikari pool HikariPool-0 is starting.
09:38:06.908 [localhost-startStop-1] INFO  (HikariDataSource.java:72) com.zaxxer.hikari.HikariDataSource - Hikari pool HikariPool-0 is starting.
09:38:35.556 [localhost-startStop-1] INFO  (HikariDataSource.java:72) com.zaxxer.hikari.HikariDataSource - Hikari pool HikariPool-0 is starting.
09:38:46.284 [localhost-startStop-1] INFO  (HikariDataSource.java:72) com.zaxxer.hikari.HikariDataSource - Hikari pool HikariPool-0 is starting.
09:39:00.006 [localhost-startStop-1] INFO  (HikariDataSource.java:72) com.zaxxer.hikari.HikariDataSource - Hikari pool HikariPool-0 is starting.
09:39:23.584 [localhost-startStop-1] INFO  (HikariDataSource.java:72) com.zaxxer.hikari.HikariDataSource - Hikari pool HikariPool-0 is starting.
09:39:26.272 [localhost-startStop-1] INFO  (HikariDataSource.java:72) com.zaxxer.hikari.HikariDataSource - Hikari pool HikariPool-1 is starting.
09:39:27.064 [localhost-startStop-1] INFO  (HikariDataSource.java:72) com.zaxxer.hikari.HikariDataSource - Hikari pool HikariPool-2 is starting.
09:39:38.270 [localhost-startStop-1] INFO  (HikariDataSource.java:72) com.zaxxer.hikari.HikariDataSource - Hikari pool HikariPool-0 is starting.
09:39:52.263 [localhost-startStop-1] INFO  (HikariDataSource.java:72) com.zaxxer.hikari.HikariDataSource - Hikari pool HikariPool-0 is starting.
09:39:54.643 [localhost-startStop-1] INFO  (HikariDataSource.java:72) com.zaxxer.hikari.HikariDataSource - Hikari pool HikariPool-1 is starting.
09:40:17.917 [localhost-startStop-1] INFO  (HikariDataSource.java:72) com.zaxxer.hikari.HikariDataSource - Hikari pool HikariPool-0 is starting.
09:40:45.936 [localhost-startStop-1] INFO  (HikariDataSource.java:72) com.zaxxer.hikari.HikariDataSource - Hikari pool HikariPool-0 is starting.
09:41:00.565 [localhost-startStop-1] INFO  (HikariDataSource.java:72) com.zaxxer.hikari.HikariDataSource - Hikari pool HikariPool-0 is starting.
09:41:03.900 [localhost-startStop-1] INFO  (HikariDataSource.java:72) com.zaxxer.hikari.HikariDataSource - Hikari pool HikariPool-1 is starting.
09:41:43.001 [localhost-startStop-1] INFO  (HikariDataSource.java:72) com.zaxxer.hikari.HikariDataSource - Hikari pool HikariPool-0 is starting.
