### ISSUE TITLE
Logging compression

### ISSUE THREAD

**Issue by GeorgeGkinis** [OSGP/Platform#118]
Wat staan er allemaal voor files? 
Hoe oud zijn die? 
Staan er spullen die weg mogen? 
Wordt er overbodige logging aangemaakt?

**Comment by GeorgeGkinis** [comment]
It seems that Tomcat JULI does not support log compression. We will have to use Log4J to accomplish automatic compression of log-files

**Comment by rlemmers** [comment]
Which files exactly should be cleaned or compressed? Linux's "logrotate" utility and configuration of the logging in httpd and our application can also help.

**Comment by GeorgeGkinis** [comment]
Well, actually just adding a .gz extension for the filename in the rolling policy element within the *-logback.xml file for the app seems to do the trick. We don't need to use any external tool. I suggest only compressing the rolling files as it might be more resource consuming to compress the active log files.  Of course we could possibly compress the daily files too. They are text files so we could expect at least 80% compression. We will only have big files for one day (if timeouts etc. occur). As it is, we keep logs for 10 days which is not that much disk usage if they are compressed. We could easily reduce the total log disk usage from 1GB to ~300MB just by compressing the rotated files and leaving the daily logs uncompressed. This way we wont need to change the amount of information being logged and will save development time.

**Comment by GeorgeGkinis** [comment]
http-logs
days kept : 30
size total : 22M
actions : No need to compress.
----------------------------------------------------------
osp-logs
days kept : 10, daily rolled.
size total : 1GB

biggest files : platform.log (10-250 MB) ,web-api-net-management.log (200Kb - 100MB)
the size of the rest is insignificant.
actions : We should compress the rotated files for all apps to keep uniformity. 
----------------------------------------------------------
Tomcat-logs
biggest files : catalina.out (500MB), localhost_access_log(small -> 19MB)

catalina.out :
	days kept : 4 weeks, weekly rolled
	size total : 599MB
	actions : since 26-07-15 the rolled logs are zipped. There are also files going back    to 04-11-2014 but they are small.
	 I suggest to roll this file daily and compress it to reduce the size of the daily log file. for this week it is already 495MB!!
	
localhost_access_log:
	days kept : forever! ,rolled daily.
	size total : 91MB
	actions : determine max days to keep (4 weeks, daily rolled?) and compress.

**Comment by GeorgeGkinis** [comment]
Catalina.out is logrotated by logrotate. It's configuration file resides in : /etc/logrotate.d/tomcat7

/var/log/tomcat7/catalina.out {
    copytruncate
    weekly
    rotate 52
    compress
    missingok
    create 0644 tomcat tomcat
}

I would like to change this to : 

/var/log/tomcat7/catalina.out {
    copytruncate
    daily
    rotate 7
    compress
    missingok
    create 0644 tomcat tomcat
}

**Comment by GeorgeGkinis** [comment]
The Catalina logs are sucessfully being compressed by logrotate.

**Comment by GeorgeGkinis** [comment]
The catalina logs are automatically being compressed by logrotate.
The logback.xml for all wabapps are modified and a pull request is sent.
They still need to be deployed. There wil be some downtime needed to reload the logback.xml files.
