### ISSUE TITLE
Investigate why platform.log is very large sometimes

### ISSUE THREAD

**Issue by GeorgeGkinis** [OSGP/Platform#119]
The size of platform.log is normally around 10M for one day. On certain days it's over 200M, probably because of errors. Find out what the cause is.

**Comment by GeorgeGkinis** [comment]
A stack trace is logged in the folowing occasions within the platform.log and catalina.out: 

- Sequence number incorrect (419 times today) : Unexpected exception from downstream. {}
com.alliander.osgp.platform.domain.exceptions.PlatformException: SequenceNumber incorrect (stack trace follows...)

- NullPointerException (1419 times today) : PublicLightingSetTransitionRequestMessageProcessor - Error while processing message
java.lang.NullPointerException: null (stack trace follows ...)

- Connection timeout (30000ms) (6410 times today ) : PublicLightingSetTransitionRequestMessageProcessor - Error while processing message
java.io.IOException: Failed to receive response within timelimit 30000 ms (stack trace follws...)

- Unable to connect (2866 times today) : PublicLightingSetTransitionRequestMessageProcessor - Error while processing message
java.io.IOException: Unable to connect (stack trace follows...)

These seem to be the main reason the log files are so big.

We could :
- Fix the bugs (if they can be fixed and are not caused by some external reason)
- Compress the rolled logs to keep the information and save disk space.

**Comment by rlemmers** [comment]
What is the cause for those errors? "Unable to connect" sounds like one or more devices are unreachable. That's not cause by a bug, but we should implement an improvement to limit the number of attempts to connect to such a device.

Compressing older logs is always good, but we also need to fix the underlying issue of generating so much logging.

**Comment by GeorgeGkinis** [comment]
As with the logging database analysis, the issue of excessive llogging occurs when the platform tries to connect to a device that is not responding.. Actions to solve this could be : 

Not logging the specific exceptions
Not trying to connect with a device if it has not registered within the last 2 hours. (preferred)

**Comment by rlemmers** [comment]
I will create a new issue to communicate less often with devices that didn't respond to a previous call.
