### ISSUE TITLE
Database logging too big

### ISSUE THREAD

**Issue by GeorgeGkinis** [OSGP/Platform#120]
The osp_logging database on production is currently a total of 4.3Gb. We definetely neet do perform a data dump and truncate the table to save space.
The var partition where the db resides only has 400Mb left and shares the application logs which can be more than 100Mb for a day. :

Filesystem      Size  Used Avail Use% Mounted on
/dev/sdc3        19G   18G  406M  98% /var

**Comment by GeorgeGkinis** [comment]
The first entry was made on : Tue, 04 Nov 2014 15:57:50 GMT

**Comment by GeorgeGkinis** [comment]
An analysis of the most frequently ocurring error messages and the amount of messages per day in august is created and sent via  email to Ruud, Sander and Kevin with title 'Database logging analyse' at ma 24-8-2015 14:54. In general the main cause of excessive logging is exceptions and stack traces when the platform cannot connect to a device. Actions to solve this could be : 
- Not logging the specific exceptions
- Not trying to connect with a device if it has not registered within the last 2 hours. (preferred)

**Comment by rlemmers** [comment]
Old files were removed to resolve the immediate issue of available disk space.
For the longer run, I created issue 129 to solve the issue of communicating less often with devices that didn't respond to a previous call to reduce the number of database entries for logging.
