### ISSUE TITLE
Speed up Liander monitoring CSV creation

### ISSUE THREAD

**Issue by GeorgeGkinis** [OSGP/Platform#131]
ManageEngine call : 3055

**Comment by rlemmers** [comment]
Also determine the performance consequences of inserting items into the oslp_log_item table, when adding this index. An alternative solution for the issue is registering the last action in the oslp_device table.

**Comment by kevinsmeets** [comment]
@rlemmers I added this issue to Milestone 21, can you add this to **release 2** please?

**Comment by rlemmers** [comment]
Adding an index doesn't work, a different solution needs to be realized.
