### ISSUE TITLE
Emergency plan

### ISSUE THREAD

**Issue by GeorgeGkinis** [OSGP/Platform#141]
## Decide 
- Backup and Restore
- actions to be taken in the case of emergency.
- R3, R2 or both? (SSS Decides)

**Comment by GeorgeGkinis** [comment]
SSS should decide for which version a backup and Restore plan should be created.

**Comment by GeorgeGkinis** [comment]
related to #26

**Comment by Sander3003** [comment]
Please use the private sss communication channels for non-community related topics.

**Comment by GeorgeGkinis** [comment]
Moved to smartsocietyservices/webapps #95.
Closing.
