### ISSUE TITLE
Security management

### ISSUE THREAD

**Issue by GeorgeGkinis** [OSGP/Platform#142]
## Password management
- KeePass created

**Comment by GeorgeGkinis** [comment]
KeePass is to be placed somewhere safe and accesible.
Is Sharepoint the best place?
How are updates to be distributed?

**Comment by Sander3003** [comment]
You might want to discuss this topic outside the public OSGP Github.

**Comment by GeorgeGkinis** [comment]
Moved to smartsocietyservices/webapps #94
Closing.
