### ISSUE TITLE
Create signing server for PA-OSLP

### ISSUE THREAD

**Issue by kevinsmeets** [OSGP/Platform#163]
A signing server needs to be created, which receives unsigned messages from the PA via a queue. It returns a signed message to the PA via a queue.

Decouple the signing of messages from the protocol adapter.

- create new project 'signing-server'
- the project should deployable in tomcat
- the project should listen for messages coming in using a queue
- the project should sign the message
- the projects should send the signed message back to the protocol adapter using a queue

also see SSS/91

**Comment by klvries** [comment]
All bugs are solved
Documentation on github is added
alle oslp requests work still fine now
