### ISSUE TITLE
Retrieve events: according to the definition the equipment_identifier has exactly 17 chars

### ISSUE THREAD

**Issue by klvries** [OSGP/Platform#167]
Retrieve events: according to the definition the equipment_identifier has exactly 17 chars

See the specs for the shipment file:
Alliander projects > Smart Metering Project File > 010 (System documentation) > 020 (Requirements) > Documentatie Infostroom > Shipment file   >  20122013-DSMR-4.0-Shipment-File-definition-v2.5.4

Now in the retrieve events also shorter identifiers can be used.

**Comment by kevinsmeets** [comment]
I have changed the XSD.

**Comment by kevinsmeets** [comment]
See Platform build:
http://54.77.62.182/view/Development/job/OSGP_Platform_development/190/

And webapps build:
http://the-other-build-server.kevin.com:8080/view/OSGP-Git/job/OSGP_Webapps_development/69/
