### ISSUE TITLE
good, up to date documentation (wiki?) to promote and support contributors

### ISSUE THREAD

**Issue by eduarddrenth** [OSGP/Platform#214]

**Comment by Sander3003** [comment]
Please keep the converstations in english so non-dutch speakers can read along (lower the barrier to join)

**Comment by eduarddrenth** [comment]
github offers wiki functionality, see for example https://github.com/OSGP/Platform/settings

**Comment by Sander3003** [comment]
We decided to go with Gitbook so we can do versioning on documentation and re-use the development flow used for software development. 

http://54.77.62.182/job/OSGP_Documentation_development/lastSuccessfulBuild/artifact/_book/index.html 

You can use "fix this page" to modify pages. This gets close to the Github wiki features.

**Comment by eduarddrenth** [comment]
ok

**Comment by Sander3003** [comment]
I think that the question about up-to-date an complete documentation is relevant. My feeling is that improvement is possible and needed. @phoutman confirms this. @eduarddrenth do you have any suggestions how we can improve this?
