### ISSUE TITLE
Add offset for light measurement switching to OSLP [partly RTM-100-025]

### ISSUE THREAD

**Issue by rlemmers** [OSGP/Platform#234]
## User story
As a Net Manager or municipality user
I want to configure a positive offset for switching a lighting device
so I have more detailed control over the burning hours of a device

**Comment by rlemmers** [comment]
@marcelvanhal what is the priority for this user story?

**Comment by WalterBorgstein** [comment]
Didn't we agree to no implement this?

**Comment by rlemmers** [comment]
Indeed, we should close this story.
