### ISSUE TITLE
Interface with Jasper Wireless

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#240]
Find out how the interface (API) with Jasper Wireless works.
Documentation can be found online.
This api is responsible for sending a sms to a smart meter
The result of this story is a document (README) that describes how to configure and use this library for sending an sms

**Comment by mvhaasteren** [comment]
Documentation can be found at:
https://weblinks.nl.cgi.com/sites/032448/Smart%20Metering%20Project%20File/Forms/,DanaInfo=.awt3CiszGkpsKo10+AllItems.aspx?RootFolder=%2fsites%2f032448%2fSmart%20Metering%20Project%20File%2f010%20%28System%20documentation%29%2f020%20%28Requirements%29%2fDocumentatie%20Infostroom%2fJWCC%20-%20Jasper%20Wireless&FolderCTID=0x012000CE099E2FD464DF4594FCB9CADBDCBC21&View=%7b00839F0C-AEEA-4F16-9B11-BB306931267B%7d

**Comment by Sander3003** [comment]
Is this documentation also public available?

**Comment by mvhaasteren** [comment]
Nope. It was ment as background information for colleagues and testers.
On suggestion of Abdel I remove the link.

**Comment by Sander3003** [comment]
If their is a public copy available, you can link to that website.
