### ISSUE TITLE
How Alarm Notification is coming in OSGP

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#241]
Find out how:
- An Alarm Notification Message, sent by the meter, is coming into the OSGP system.
- How to interpret an Alarm Notification Message (content of the message)
- How to communicate the result to the integration layer
- OSGP should probably listen to incoming traffic on a certain port. Investigate if the Fraunhofer library has support for this.

Documentation can be found on OSGP portal.

**Comment by bvdzwet** [comment]
Based on DSMR P3 9.3 Push Setup and DLMS Blue Book ed. 12 4.4.8.1 Overview of Push interface classes and objects, it is my understanding that we will have to listen for TCP connections by the meter.
For the Push Setup Alarm we will receive some bytes. These bytes consist of two pieces of information separated by byte 0x2C (a comma). The bytes before the comma are input for a string that gives the device identification (specifically the value on the meter for Device ID 2 [0-0:96.1.1.255]). The (4) bytes following the comma are the bytes for the double-long-unsigned value of the Alarm Object (0-0:97.98.0.255).

I assume the meter will send these bytes to an address that is configured in the Push Setup Alarm (0.1.25.9.0.255) attribute 3 Send Destination and Method. The octet-string that is part of this attribute can be used to create a string, that is of the form host name + colon + port number.
Yet to be tested is setting up a server listening for TCP connections, configuring the send destination to this endpoint, and triggering an alarm notification.
The handling of this notification on the TCP endpoint will need to propagate the information obtained to the rest of the platform.
