### ISSUE TITLE
Handle shipment file Gas

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#267]
### Story: handle shipment file for G meter
```
As grid operator
I want OSGP to be able to handle the shipment file for  the G meters. 
So that I the meter is added to OSGP, master data and the security keys from the meters are stored in OSGP
```

**Comment by robindenadel** [comment]
waiting for an example of a shipment file

**Comment by robindenadel** [comment]
201510191700-dsmrg4-alditg4501755308-00020-G4-RF1eWL-2mtrs is an example of a shipment file for G meter

**Comment by robindenadel** [comment]
waiting for the restructuring work for Device / Smart Meter / Public Lighting entities
