### ISSUE TITLE
Firmware upgrade E

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#268]
### may be combined with osgp/platform#275
```
```

### Story: upgrade the firmware from the E meter
```
As grid operator
I want OSGP to be able to upgrade the firmware of a given E meter. 
So that I the meter gets a new firmware version in order to work 
correctly with the new version.
```

**Comment by robindenadel** [comment]
waiting for  OSGP/Platform#300

**Comment by robindenadel** [comment]
We assume the device needs 1 upgrade (not a few after each other) to be up-to-date
