### ISSUE TITLE
Figure out how firmware upgrade works

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#275]
### The firmware upgrade process is described in detail in the Bluebook version 10
Image Block Transfer Mechanism is used to transfer a Firmware Image to an E meter. 
Image Transfer Process from COSEM Client to COSEM Server uses Image Read Services to read ImageBlocks from Image and Image Block Transfer Services to transfer the ImageBlocks to COSEM Server.

**Comment by robindenadel** [comment]
See Blue Book 10 page 63 and further

**Comment by rlemmers** [comment]
@robindenadel when initializing the communication with a COSEM server, the server and client automatically exchange the block sizes that they support.

**Comment by bvdzwet** [comment]
Based on what I read in the DLMS Blue Book (4.4.4.4 The Image transfer IC definition), there appears to be a specific attribute for the image block size (2. image_block_size of class 18), a note is included in the documentation that this should not exceed the ServerMaxReceivePduSize negotiated.
I think @rlemmers is referring to this size in his reply to @robindenadel.
Based also on DSMR P3 (5.12 Firmware upgrade), I believe the image block size to be used should be based on the attribute I mentioned of the Image Transfer class.
The image_block_size attribute of the Image Transfer object can be retrieved by getting the value for class id 18, obis code 0.0.44.0.0.255, attribute id 2 from the meter.
