### ISSUE TITLE
Store IP address for a meter

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#277]
## User story
```
As a Net Manager
I want to support storage of dynamic IP addresses for meters
so I know how to send a message a certain meter
and so I don't need to rely fixed IP addresses, which are more expensive and scarce
```

### Store IP address
```
Given a meter with id 54321 is defined in the system
When a wake up notification is received from meter 54321
Then we store the IP address from which we received the wake up notification
```

### Use IP address
```
Given a meter with id 54321 is online
When we have a request for meter 54321
Then we can send the request to the meter by using its stored IP address
```

Note: a large part of this will probably be realized already by the restructuring work for the Device / Smart Meter / Public Lighting entities.

**Comment by robindenadel** [comment]
waiting for the restructuring work for Device / Smart Meter / Public Lighting entities

**Comment by bvdzwet** [comment]
The IP address stored in the osgp_core device table as network_address is now used for the communication with smart meters. Information for smart meters in osgp_core is now spread between the device table for information common to all types of devices and the smart_metering_device table for information specific to smart meters.
These changes are a result of part of the work done for OSGP/Platform#274 (Change device and smartmeter entities).
