### ISSUE TITLE
Communicate with smart meters over GPRS

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#283]
### Story : communicate with smart meters over GPRS
```
Always-on:
Be able to select that communication mode : via GPRS 

On demand:
Be able to discover that the meter has an active communication session / started
Can deal with dynamic IP addresses of the meters. 
Can handle jobs that not directly can be sent  to the meter.
```

**Comment by rlemmers** [comment]
If a GPRS device has a dynamic IP address, OSGP has to be able to handle those. I will check if that's already supported.

**Comment by rlemmers** [comment]
@elhachhouchi can we close this item? We already communicate over GPRS and dynamic IP addresses can be handled by the code (after Kevin's refactoring). Handling jobs and active/inactive communication sessions will be part of #187 (Send an SMS wake up message).
