### ISSUE TITLE
Status of setting a tariff schedule does not work when the error response comes from the device

### ISSUE THREAD

**Issue by kevinsmeets** [OSGP/Platform#287]
When setting a tariffschedule the end result is no longer shown in the device overview. It seems that the icon with the two arrows is shown and never dissappears.

For device PSLD_14-35-EHV-001 it is not allowed to set a tariffschedule, as this device is a PSLD type which doesn't support tariffswitching. In the log the error is printed: "com.alliander.osgp.domain.core.exceptions.ValidationException: Set tariff schedule is not allowed for PSLD". This message should be shown in the tooltip of the little triangle with the exclamation mark. However, the icon with the two arrows is continiously shown.

It seems that the implementation of error handling has changed (most likely during the Fault Tolerance implementation). Instead of a response message containing NOT_OK and an errormessage, a SOAPFault is returned. The backend of the netmanagement application (web-api-net-management) doesn't handle the SOAPFault very well. The result is that the tariff_status column of the device table in osp_net_management_web database is never updated with the errormessage. This means that the frontend will show the icon with the two arrows for ever, and the errormessage is never shown. If one waits long enough, a message is printed in the javascript console of the browser: 'max amount of polling reached, giving up.'

**Comment by klvries** [comment]
This is for instance the case for setting a tariff schedule for a device of type PSLD.
On the testserver PSLD_14-35-EHV-001
