### ISSUE TITLE
The response on the 'RetrieveActualMeterReads' is compliant with the xsd when the meter is new

### ISSUE THREAD

**Issue by klvries** [OSGP/Platform#311]
The response on the 'RetrieveActualMeterReads' is compliant with the xsd when the meter is new

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header/>
   <SOAP-ENV:Body>
      <ns3:ActualMeterReadsResponse xmlns:ns2="http://www.alliander.com/schemas/osgp/common/2014/10" xmlns:ns3="http://www.alliander.com/schemas/osgp/smartmetering/sm-monitoring/2014/10" xmlns:ns4="http://www.alliander.com/schemas/osgp/smartmetering/sm-configuration/2014/10">
         <ns3:ActiveEnergyImport>0</ns3:ActiveEnergyImport>
         <ns3:ActiveEnergyExport>0</ns3:ActiveEnergyExport>
         <ns3:ActiveEnergyImportTariffOne>0</ns3:ActiveEnergyImportTariffOne>
         <ns3:ActiveEnergyImportTariffTwo>0</ns3:ActiveEnergyImportTariffTwo>
         <ns3:ActiveEnergyExportTariffOne>0</ns3:ActiveEnergyExportTariffOne>
         <ns3:ActiveEnergyExportTariffTwo>0</ns3:ActiveEnergyExportTariffTwo>
      </ns3:ActualMeterReadsResponse>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

com.eviware.soapui.impl.wsdl.teststeps.assertions.basic.SchemaComplianceAssertion@1807cb24
line 5: Expected element 'LogTime@http://www.alliander.com/schemas/osgp/smartmetering/sm-monitoring/2014/10' instead of 'ActiveEnergyImport@http://www.alliander.com/schemas/osgp/smartmetering/sm-monitoring/2014/10' here in element ActualMeterReadsResponse@http://www.alliander.com/schemas/osgp/smartmetering/sm-monitoring/2014/10
line 6: Expected element 'LogTime@http://www.alliander.com/schemas/osgp/smartmetering/sm-monitoring/2014/10' instead of 'ActiveEnergyExport@http://www.alliander.com/schemas/osgp/smartmetering/sm-monitoring/2014/10' here in element ActualMeterReadsResponse@http://www.alliander.com/schemas/osgp/smartmetering/sm-monitoring/2014/10
line 7: Expected element 'LogTime@http://www.alliander.com/schemas/osgp/smartmetering/sm-monitoring/2014/10' instead of 'ActiveEnergyImportTariffOne@http://www.alliander.com/schemas/osgp/smartmetering/sm-monitoring/2014/10' here in element ActualMeterReadsResponse@http://www.alliander.com/schemas/osgp/smartmetering/sm-monitoring/2014/10
line 8: Expected element 'LogTime@http://www.alliander.com/schemas/osgp/smartmetering/sm-monitoring/2014/10' instead of 'ActiveEnergyImportTariffTwo@http://www.alliander.com/schemas/osgp/smartmetering/sm-monitoring/2014/10' here in element ActualMeterReadsResponse@http://www.alliander.com/schemas/osgp/smartmetering/sm-monitoring/2014/10
line 9: Expected element 'LogTime@http://www.alliander.com/schemas/osgp/smartmetering/sm-monitoring/2014/10' instead of 'ActiveEnergyExportTariffOne@http://www.alliander.com/schemas/osgp/smartmetering/sm-monitoring/2014/10' here in element ActualMeterReadsResponse@http://www.alliander.com/schemas/osgp/smartmetering/sm-monitoring/2014/10

**Comment by rudidevries** [comment]
@klvries How can I recreate this situation? Which meter did you use?
