### ISSUE TITLE
Handle shipment file Encrypted

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#312]
As grid operator
I want OSGP to be able to handle an encrypted shipment file
So that I the meters are be added to OSGP and with their master data and security keys are stored in OSGP

**Comment by robindenadel** [comment]
Scenario: handle encrypted shipment file successfully

Given shipment file encrypted.xml
When the shipment file is put in the directory indicated by the shipment.directory.import.encrypted parameter
Then the ShipmentFileStatus is set to IN_PROGRESS
And the following data is stored:
| Company | LIANDER |
| Supplier | KAIFA |
| Device_type | MA105C |
| Serial_number | 0000141227 |
| Device_batch_number | DBN2014072202 |
| Communication_method | GPRS |
| Year_of_manufactory | 2014 |
| Hardware_version | 050302 |
| Module_active_firmware_version | 05010083 |
| Core_active_firmware_version | 05010108 |
| Communication_provider | KPN |
| Communication_provider_batch_id | 7356 |
| ICC_id | 8931086214024039846 |
| IMSI | 204080803419834 |
| IMEI | 013777007386905 |
| PPP_authentication_user | E9998000014122714 |
| Equipment_identifier | E9998000014122714 |
| Kema_gastec_code | E9998 |
| DSMR_ version | 4.2.2 |
| HLS3_active | 0 |
| HLS4_active | 0 |
| HLS5_active | 1 |
| Master_key | bd9f2b5b3f1279d9ae3bcf828dc71a62 |
| Global_encryption_unicast_key | af1835c9889a51f1890aaa7f7ac6a013 |
| Authentication_key | f790cf0d088d78224d39d23567f95ee8 |
And the ShipmentFileStatus is set to DONE
And the shipment file is moved to the DONE directory indicated by the shipment.directory.done.encrypted parameter
