### ISSUE TITLE
Web service logging does not work for calls returning a soap fault

### ISSUE THREAD

**Issue by smvdheijden** [OSGP/Platform#36]
For the Fault Tolerance feature the behaviour of the web services has changed. In stead of a response with not ok, a soap fault is returned.  As a result I expect there will be no web service logging, which is using the web service response, present.

First test if the ws service logging indeed fails as expected in case of soap fault.
If so, add the appropriate logging...

**Comment by klvries** [comment]
This error is testwed on the new logging module 'opsp_logging'

The SOAP faults are logged correct in the table "web_service_monitor_log"

so this issue can be closed
