### ISSUE TITLE
Support realistic delays in device simulator

### ISSUE THREAD

**Issue by smvdheijden** [OSGP/Platform#50]
Support realistic delays in device simulator

**Comment by smvdheijden** [comment]
The delay should be a random configurable interval, not a fixed 1 second delay

**Comment by klvries** [comment]
The device-simulator supports now delays.
The delay is configurable:


response.delay.time2000
response.delay.random.range=2000

The settings work fine.

In the logging the following is visible:

12:05:42.788  27863 [New I/O worker #6] INFO  c.a.o.w.service.OslpChannelHandler - Sleeping for 3595 milliseconds
