### ISSUE TITLE
Implement automatic event sending in device simulator

### ISSUE THREAD

**Issue by smvdheijden** [OSGP/Platform#51]
As OSGP we want the device simulator to automatically sent event notifications on switching, rebooting, etc. in order to behave more like a real device during performance testing.

It's unclear if any functionality remains, because we'll already implement automatic events for tariff switching, light switching and autonomous reboots.

**Comment by rlemmers** [comment]
Closing this issue, because of the unclarity. If additional functionality is needed for automatically sending events, open a new issue describing exactly what's needed.
