### ISSUE TITLE
Consolidate logging - restructure DBs

### ISSUE THREAD

**Issue by rlemmers** [OSGP/Platform#75]
Subtasks:
- Rename DB osgp_ws_logging to osgp_logging.
- Migrate content from table oslp_log_item in DB osgp_core to the new device_log_item table. Afterwards, remove the oslp_log_item table.

Part of BI #74.

**Comment by klvries** [comment]
All logging is now concentrated in the osgp_logging DB ias
It works fine and as described.

So this issue can be closed.
