### ISSUE TITLE
Consolidate logging - retrieve device messages from device_log_item

### ISSUE THREAD

**Issue by rlemmers** [OSGP/Platform#76]
The OSGP Management App retrieves the device messages. These messages are no longer available in the osgp_core DB. Let the OSGP Management App retrieve those messages from the new location (table device_log_item in DB osgp_logging).

Part of BI #74.

**Comment by klvries** [comment]
The messages in web-operator  application are now correct retrieved from the  table table device_log_item in DB osgp_logging
