### ISSUE TITLE
Add a smart meter on the platform

### ISSUE THREAD

**Issue by smvdheijden** [OSGP/Platform#78]
As OSGP, we want to be able to add a smart meter to the system,
so we can start to use & manage the new meter.

Tasks:
- [ ] Define acceptance criteria
- [x] Implement in WS adapter
- [x] Implement in Domain adapter
- [x] Implement in core
- [x] Implement in DLMS protocol adapter
- [ ] Implement acceptance tests

**Comment by kevinsmeets** [comment]
I had some issues adding the new smart-meter components to FitNesse. Can somebody help me?

**Comment by kevinsmeets** [comment]
I created issue #170 ...
Then I closed this issue...
