### ISSUE TITLE
Delete old logging data

### ISSUE THREAD

**Issue by rlemmers** [OSGP/Platform#84]
Periodically clear old logging data, to prevent large growth of the operational DB.

It should be possible to have a separate retention period per table to clean.

Part of BI #81.

**Comment by klvries** [comment]
with the script cleanup.sh old data of the osgp_logging DB : web_service_monitor_log, device_log_item, logging_event,  logging_event_exception and logging_event and logging_event_property can be cleaned up.

Also the osgp_core.event table can cleaned up.

the parameters are the age of the records in days for each file and the location of the sql script.
