### ISSUE TITLE
Incorrect exception thrown when setting tariff schedule for psld

### ISSUE THREAD

**Issue by KanthanK** [OSGP/Platform#93]

**Comment by klvries** [comment]
The response now gives the correct exception:

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header/>
   <SOAP-ENV:Body>
      <SOAP-ENV:Fault>
         <faultcode>SOAP-ENV:Server</faultcode>
         <faultstring xml:lang="en">Set tariff schedule is not allowed for PSLD.</faultstring>
         <detail>
            <ns2:FunctionalFault xmlns:ns2="http://www.alliander.com/schemas/osgp/common/2014/10">
               <ns2:Code>402</ns2:Code>
               <ns2:Message>Set tariff schedule is not allowed for PSLD.</ns2:Message>
               <ns2:Component>DOMAIN_TARIFF_SWITCHING</ns2:Component>
               <ns2:InnerException>com.alliander.osgp.domain.core.exceptions.ValidationException</ns2:InnerException>
               <ns2:InnerMessage>Set tariff schedule is not allowed for PSLD.</ns2:InnerMessage>
            </ns2:FunctionalFault>
         </detail>
      </SOAP-ENV:Fault>
   </SOAP-ENV:Body>
